### ISSUE TITLE
core v1.8.0 has calls to undefined functions

### ISSUE THREAD

**Issue by javiertoledos-xumak** [justuno-com/core#380]
In the function `Core\Format\Html\Tag::openTagWithAttributesAsText` on line 37 there's a call to "df_tab_multiline" and "df_nop" functions which don't exist. One of the functions is implemented in lib/Core/text and it's called `ju_tab_multiline`. Doing a diff between version 1.7.7 and 1.8.0 it seems the old version has this correctly. However the old version is not compatible with PHP 8.1 which is required for Magento 2.4.4 or above. Since PHP 7.4 got deprecated there's a need to get this working as current versions of Magento are dropping support of unsupported PHP language versions.

**Comment by dmitry-fedyuk** [comment]
Fixed in [1.3.1](https://github.com/justuno-com/core/releases/tag/1.3.1)
